openaddresses/batch

cloudformation/batch.js, lambda/index.js, task/collect.js
Now that we have the full data loaded into a staging server, the collect scripts fail due to a batch limit of 22gb disk.
This creates a new `Mega` batch queue which has a 250gb disk and is currently only used to run `collect` jobs.
The https://github.com/openaddresses/lib has also been updated to be able to manually fire scheduled tasks
```
./cli.js --url http://staging.openaddresses.io schedule fire --type collect
```
=> Batch Environments

api/web/src/components/Log.vue
Closes: https://github.com/openaddresses/batch/issues/39
cc/ @iandees
=> Monospace Logs

task/collect.js, task/lib/job.js
S3 Objects can't be viewed in browser directly as they don't have their content-type set on s3.
Closes: https://github.com/openaddresses/batch/issues/59
cc/ @iandees
=> Add explicit ContentType

api/lib/map.js, api/web/src/components/Coverage.vue, api/web/src/components/Data.vue
In the near future we will be adding support for buildings and parcels processing to the batch platform. 
This clears the way for supporting this feature by updating the coverage map with support for visualizing the difference between `all`, `addresses`, `buildings` and `parcels`.
The map coverage can be changed by selecting a filter layer other than `any` in the filter dropdown.
=> Map Buildings & Parcels Coverage

cloudformation/batch.js
In an effort to further curtail costs, pin the batch environment to only allow up to 2 simultaneous instances and use `BEST_FIT_PROGRESSIVE` for cheaper instance selection when possible
cc/ @iandees
=> Cost Reduction

.github/workflows/ecr_api.yml, .github/workflows/ecr_task.yml, .github/workflows/lambda.yml
Only run actions on active PRs. 
- Saves us money on ECR Storage (fewer builds)
- Saves us money on S3 storage (fewer lambdas)
=> Actions Draft PR

api/lib/schema.js
Integer type definitions in JSON schemas applied to req queries would fail as req queries are always strings
- Attempt to cast req.qurey[key] to an integer if the schema requires it
=> Allow integer query schema

api/lib/run.js
Now that we have a specific priority queue for CI jobs that is elevated above scheduled jobs, differentiate between sending jobs to queues based on the run.github param
cc/ @iandees
=> CI Priority

api/lib/batch.js, api/lib/ci.js, api/lib/run.js, api/lib/schema.js, api/test/ci.unit.test.js
Check the internal JSON Diff of a file submitted by CI and only process the sources changed. This prevents a single source change in a file of many sources from running all sources at once.
cc/ @iandees
=> Internal Diff CI

task/export.js
One of our awesome backers reported an issue with exporting a large statewide address source as a CSV (exp: 9).
From the logs it has been determined that the source failed due to an internal OGR timeout. This PR standardizes our use of the OGR library for standard timeouts, error handling, and logging.
At the moment the timeout is set to 10 minutes. I'm testing this locally to ensure that conversion happens successfully.
=> OGR Timeout

api/lib/level.js, api/test/level.srv.test.js
Org level sponsors do not have an email address returned by OpenCollective, and therefore cannot be upgraded to their appropriate level automatically.
This PR adds a rudimentary override system and pre-populates it with our current list of org level sponsors and their domain names.
As always, thanks to our sponsors for keeping this project running - and if there is a more suitable domain name I should add just LMK.
=> Override OpenCollective

api/web/public/googlecfc027a1ca15dcdb.html, api/web/public/index.html
I made nginx remove the .html extension for nicer looking urls, but that means we can't verify. Using meta tag verification instead.
=> Meta Verify

api/routes/map.js
Clouldflare is decompressing and serving MVTs resulting in MapboxGL getting raw-uncompressed MVTs which it is not happy about.
=> Tell cloudflare to not touch MVTs

api/lib/ci.js
InternalDiff is not always picking up which source to run and defaulting to running all of the layers in a source
=> InternalDiff

api/API.md
Heya,
I was checking out [the docs](https://batch.openaddresses.io/docs/) today and noticed a couple parts of the bearer authorization example which could be improved.
---
The correct format is `Authorization: <type> <credentials>`, which actually what is written in the code as `Authorization: Bearer <api token>`. Unfortunately it seems like the rendering engine is stripping that syntax:
I changed `<>` to `{}`, not sure if this will fix it, just picked different symbols 🤷‍♂️ 😆 
---
In the example it's written `'Authorization': 'oa.1234-your-token-here-5678'` which I believe should be `'Authorization': 'Bearer oa.1234-your-token-here-5678'`?
=> Update bearer authorization example

api/lib/job.js
Validated files are now postfixed with `-validated.geojson.gz to differentiate them from non-validatd files
=> Set unique name for validated files

task/export.js
We've had a couple of backers run into export failures for larger sources.
This PR makes exceptions for region/countrywide level timeouts
Closes: https://github.com/openaddresses/batch/issues/178
=> Export Timeout

api/lib/config.js, cloudformation/lib/api.js
It's easier to maintain a single service so removing MailGun config in favour of the already deployed AWS SES integration
=> Remove MailGun

task/collect.js, task/export.js, task/fabric.js, task/lib/job.js
Fixes https://github.com/openaddresses/openaddresses/issues/6376
Large objects (like the collections) were failing to upload with errors like:
```
EntityTooLarge: Your proposed upload exceeds the maximum allowed object size.
--
at Request.extractError (/usr/local/src/batch/node_modules/aws-sdk/lib/services/s3.js:711:35)
at Request.callListeners (/usr/local/src/batch/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/usr/local/src/batch/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/usr/local/src/batch/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/usr/local/src/batch/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/usr/local/src/batch/node_modules/aws-sdk/lib/state_machine.js:14:12)
at …
```
=> Use the S3 JavaScript SDK's upload function instead of putObject

api/routes/job.js
This is an attempt to clear the `data` cache (used in the endpoint that shows the list of data at batch.openaddresses.io) when a job finishes.
Likely useful for the discussion that is happening on https://github.com/openaddresses/openaddresses/issues/6376
=> Clear data cache on job finish

task/sources.js
The "OA_Sources" job from this weekend failed with:
```
[Error: ENOENT: no such file or directory, open '/usr/local/src/batch/https:/api.github.com/repos/openaddresses/openaddresses/commits/master/openaddresses.zip'] {
--
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '/usr/local/src/batch/https:/api.github.com/repos/openaddresses/openaddresses/commits/master/openaddresses.zip'
}
```
I think this happened because the call to `fetch()` in `get_sha()` ([here](https://github.com/openaddresses/batch/blob/ad8a28124cc0da07986f2a59e849638b5ce26503/task/sources.js#L142))  was calling the `fetch()` in the file instead of the built-in `fetch()` HTTP client.
This renames that `fetch()` to something else so that it doesn't shadow the built-in.
=> fetch_repo was shadowing the built-in fetch

api/lib/types/job.js
Fixes https://github.com/openaddresses/batch/issues/322 by fetching logs from the earliest point in the log stream onward, rather than the most recent logs backward (the default).
=> Fetch logs from the earliest point

api/web/src/pages/App.vue
https://batch.openaddresses.io/docs/ works but https://batch.openaddresses.io/docs redirects to http://batch.openaddresses.io:5000/docs/ and times out.
Fixes https://github.com/openaddresses/openaddresses/issues/7173
=> It looks like /docs/ needs the trailing slash

cloudformation/lib/batch.js
Sources that have https://data.openaddresses.io as a data source use [this code](https://github.com/openaddresses/batch/blob/master/task/lib/job.js#L110-L128) to make S3 requests to these buckets instead of going through the internet and incurring egress charges. The batch job role here does not have permission to get to the data.openaddresses.io bucket, though, so they fail (like [this job](https://batch.openaddresses.io/job/380762#job:380762:log:1)).
This change adds the bucket to the list of permissions on the role.
=> Include data.openaddresses.io in batch job role

api/API.md, api/routes/job.js, api/web/src/components/util/MustLogin.vue
Fixes https://github.com/openaddresses/openaddresses.io/issues/86
=> Fix some spelling mistakes

api/lib/batch.js
As part of #401 I removed the shebang from the scripts referenced here. This caused AWS Batch to fail running the commands with:
```
exec ./task.js: exec format error
```
To resolve this, I'm switching the commands run by the Batch containers to exec `node` with the script as an arg instead of trying to exec the scripts directly.
=> Eslint complained about shebang, so run these scripts with node

api/routes/github.js
The API logs are sprinkled pretty heavily with logs that look like:
```
PayloadTooLargeError: request entity too large
```
The webhooks are fairly big, but they seem to only be 30K or so, so chances are this won't fix the problem. But it's worth a try.
=> Increase the body size limit for the Github webhook

task/collect.js
My changes to add parquet writing in #394 seemingly never actually got deployed, because when Nick made some changes more recently and presumably did a deploy, the collection builds failed with the following error:
```
ok - zip created: /tmp/z8h0amnyp4p/us-midwest.zip
ok - s3://v2.openaddresses.io/batch-prod/collection-us-midwest.zip
ok - uploaded: r2://openaddresses/v2.openaddresses.io/batch-prod/collection-us-midwest.zip
ok - archive uploaded
TypeError: writer.close is not a function
at file:///usr/local/src/batch/collect.js:371:16
at new Promise (<anonymous>)
at parquet_datas (file:///usr/local/src/batch/collect.js:321:12)
at collect (file:///usr/local/src/batch/collect.js:114:22)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async cli …
```
=> Try to fix async Parquet writing

task/collect.js
Continues #394 
Don't try to convert a null or invalid GeoJSON geometry.
=> Add checks to protect against bad/unexpected geometry

task/collect.js
Continues #394 
The builds are failing now because of memory problems:
```
<--- Last few GCs --->
[1:0x7f24ff58d000] 29254311 ms: Mark-Compact 932.6 (970.2) -> 927.6 (972.9) MB, pooled: 0 MB, 1000.28 / 0.00 ms  (average mu = 0.192, current mu = 0.032) allocation failure; scavenge might not succeed
[1:0x7f24ff58d000] 29255615 ms: Mark-Compact 935.4 (972.9) -> 930.3 (975.9) MB, pooled: 0 MB, 1287.91 / 0.00 ms  (average mu = 0.098, current mu = 0.012) allocation failure; scavenge might not succeed
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----
```
This is an attempt to reduce the memory usage.
=> Reduce the row group size

task/collect.js, task/package-lock.json, task/package.json
Follows #394 
None of the parquet libraries seem to work (they get tripped up by memory leaks), so I'm trying DuckDB bindings instead.
=> Switch to using DuckDB node bindings instead of unmaintained parquet libraries

task/collect.js, task/package-lock.json, task/package.json
Follows #394 
The library added in #434 didn't work because it required a library that wasn't cross-platform compatible (arm64 vs. amd64). Trying this one instead, since it seems to be referenced on the DuckDB website (https://duckdb.org/docs/installation/?version=stable&environment=js)
=> Switch DuckDB node bindings

task/Dockerfile
Follows #394
My attempt at a fix in #435 failed. DuckDB is still trying to load bindings and fails in Alpine linux:
```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/src/batch/node_modules/@duckdb/node-bindings-linux-x64/libduckdb.so)
at Object..node (node:internal/modules/cjs/loader:1732:18)
at Module.load (node:internal/modules/cjs/loader:1289:32)
at Function._load (node:internal/modules/cjs/loader:1108:12)
at TracingChannel.traceSync (node:diagnostics_channel:322:14)
at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
at Module.require (node:internal/modules/cjs/loader:1311:12)
at require (node:internal/modules/helpers:136:16)
at getNativeNodeBinding (/usr/local/src/batch/node_modules/@duckdb/node-bindings/duckdb.js:9:2 …
```
=> Switch away from alpine linux base image
