openaddresses/batch

api/web/src/components/Data.vue

Add missing source pane

---

api/web/src/components/Data.vue

Clear filter & show close

---

api/web/src/App.vue
api/web/src/components/Coverage.vue
api/web/src/components/Data.vue

Closes: https://github.com/openaddresses/batch/issues/6

Filter Point

---

api/web/src/components/Errors.vue

Closes: https://github.com/openaddresses/batch/issues/38

Add log button to job error page

---

api/doc/api_data.js
api/doc/api_data.json
api/doc/api_project.js
api/doc/api_project.json
api/index.js
api/lib/auth.js
api/lib/email.js
api/package.json
api/schema.sql
api/web/src/components/Forgot.vue
api/web/src/components/Login.vue
api/web/src/components/Reset.vue
api/web/src/main.js
api/web/vue.config.js
api/yarn.lock
cloudformation/api.js
cloudformation/batch.js
package.json

Allow the user to reset their password using a reset token sent to the email on file.

Password Reset

---

api/lib/auth.js
api/web/src/components/profile/ProfileTokens.vue

Fix a UI bug around token creation that would prevent the user from creating more than a single token without refreshing the page.

Token Creation

---

task/Dockerfile

Fixed: https://github.com/openaddresses/batch/issues/51
Ref: https://github.com/openaddresses/machine/pull/776

Use batch machine

---

README.md
api/web/src/components/Errors.vue

Closes: https://github.com/openaddresses/batch/issues/36

Job loading

---

api/lib/ci.js
api/lib/run.js
api/package.json
api/web/src/App.vue
api/web/src/components/Errors.vue
api/yarn.lock
cloudformation/api.js
lambda/yarn.lock
task/yarn.lock
yarn.lock

Create a GH Issue on a PR with an image of the data
**Note**: This is not a replacement for looking at the stats on the job page itself before merging.
Closes: https://github.com/openaddresses/batch/issues/20

Github Issues

---

api/yarn.lock
test

With the next round of work I would like to focus on significantly strengthening tests before I expand the scope to cover parcels/buildings.
This increases the scope of testing to perform basic code coverage

Code Coverage

---

api/lib/ci.js
api/lib/run.js
api/web/src/components/Profile.vue

The GH integration currently only supports pushes in the OA repo itself. This PR expands this support to also run our data-pls bot on PRs and subsequent commits to them.

Pull Request Support

---

api/lib/run.js
api/web/yarn.lock
api/yarn.lock
task/lib/job.js
task/task.js
task/yarn.lock
yarn.lock

Closes: https://github.com/openaddresses/batch/issues/53
Closes: https://github.com/openaddresses/batch/issues/42

Add check_source for year & skip tag

---

api/doc/api_data.js
api/doc/api_data.json
api/doc/api_project.js
api/doc/api_project.json
api/index.js
api/lib/auth.js
api/web/src/components/profile/ProfileAdminUser.vue
api/web/src/components/util/Pager.vue
api/web/yarn.lock

Our user list is nearly a mile long. This adds the ability to search for a given user as well as a default paging behavior.

User Pager

---

task/Dockerfile

Pull from [batch-machine](https://github.com/openaddresses/batch-machine) instead of using sub-components of machine itself.
This will allow cleaner development to add support for buildings & parcels

Batch Machine

---

cloudformation/batch.js

Closes: https://github.com/openaddresses/batch/issues/78

Use C5 family

---

cloudformation/batch.template.js
package.json
yarn.lock

Update `batch-alarms@1.1.0` which adds support for automatic CW Dashboard Creation

AWS CW Dashboard

---

task/package.json
task/yarn.lock

Add support for the `get` function in OA schemas
cc/ @macieg

OA Schema Update

---

api/web/package.json
api/web/yarn.lock
api/yarn.lock
yarn.lock

Maintenance PR updating core deps and updating to mapbox-gl for faster load time

Deps Update

---

api/web/package.json
api/web/yarn.lock
api/yarn.lock
lambda/yarn.lock
task/yarn.lock
yarn.lock

Keep our core dependencies fresh and updated

Core Deps Update

---

api/index.js
api/lib/auth.js
api/lib/error.js
api/package-lock.json
api/package.json
api/test/authtoken.unit.test.js
api/test/collections.test.js
api/test/init.js
api/test/job.unit.test.js
api/test/map.unit.test.js
api/test/run.srv.test.js
api/test/run.unit.test.js
api/test/user.srv.test.js

User API Validation

---

.github/workflows/ecr_task.yml
task/Dockerfile
task/package-lock.json
task/package.json

Update the schema to allow parcel sources
Ref: https://github.com/openaddresses/openaddresses/pull/5477

OA Parcel Schema

---

.github/workflows/ecr_task.yml
task/Dockerfile

We build all the deps for batch-machine each time. Let's prebuild them as a layer instead

Prebuild Batch-Machine Images

---

cloudformation/api.js
task/Dockerfile

- Preview was broken due to the switch to WKTs
- Add support for calculating centroids of polygons for viz

batch-machine@7.6.5

---

api/doc/api_data.js
api/doc/api_data.json
api/doc/api_project.js
api/doc/api_project.json
api/index.js
api/lib/job.js
api/lib/joberror.js
api/lib/util.js
api/schema.sql
api/schema/req.body.ErrorModerate.json
api/schema/res.ErrorSingle.json
api/test/fixtures/get_schema.json
api/test/job.unit.test.js
api/web/package-lock.json
api/web/package.json
api/web/src/components/Data.vue
api/web/src/components/Errors.vue
api/web/src/components/ErrorsModerate.vue
api/web/src/components/History.vue
api/web/src/components/Job.vue
api/web/src/components/Jobs.vue

Closes: https://github.com/openaddresses/batch/issues/47
Allow showing different data layers for the same geographic layer gracefully
Add consistent icons to take up less space
Add a `LICENSE` field in the `Job` object for future license data storage

UI Improvements

---

api/package-lock.json
api/package.json
api/web/package.json
package-lock.json
task/collect.js
task/lib/job.js
task/lib/stats.js
task/lib/validator.js
task/package-lock.json
task/package.json
task/test/job.test.js
task/test/stats.test.js
task/test/validator.test.js

Add stats for address validity
Partially solves: https://github.com/openaddresses/batch/issues/37

Address Validity

---

api/index.js
api/lib/auth.js
api/lib/email.js
api/lib/schema.js
api/package.json
api/schema.sql
api/schema/req.body.ForgotLogin.json
api/schema/req.query.VerifyLogin.json
api/test/fixtures/get_schema.json
api/test/user.srv.test.js
api/web/src/components/Login.vue
api/web/src/components/Register.vue
api/web/src/components/Verify.vue
api/web/src/main.js

- Add actual body error responses in UI for login events  - formerly it was a generic error
- Automatically send a verification email upon user registration
- Add verify endpoint for email token verification
Closes: https://github.com/openaddresses/batch/issues/45

Email Verification

---

task/package.json

Update to support building polys

Batch-Machine@7.7.0

---

api/lib/auth.js
api/lib/joberror.js
api/schema.sql
api/schema/res.ErrorCreate.json
api/schema/res.ErrorList.json
api/schema/res.ErrorModerate.json
api/schema/res.ErrorSingle.json
api/test/job_error.srv.test.js
api/web/src/components/Errors.vue
api/web/src/components/Job.vue

- Add extensive unit testing to Job Errors API
- Modify API to allow jobs to have multiple job errors
Closes: https://github.com/openaddresses/batch/issues/121

Job Error Refresh

---

api/lib/batch.js

Part of the solution for https://github.com/openaddresses/batch/issues/129

Add default 6h timeout

---

api/lib/user.js

Allow full regexp user filtering

Regexp User Filtering

---

api/lib/config.js

GH Push events seem to be failing as the AppID is not being passed in

GH Push Fix

---

task/Dockerfile

Ref: https://github.com/openaddresses/batch-machine/pull/5

machine@7.7.1

---

task/Dockerfile

machine@7.7.2

---

api/.dockerignore
api/Dockerfile
api/doc/api_data.js
api/doc/api_data.json
api/doc/api_project.js
api/doc/api_project.json
api/index.js
api/lib/cacher.js
api/lib/map.js
api/package-lock.json
api/package.json
api/test/fixtures/get_schema.json
api/web/src/components/Coverage.vue
api/web/src/components/Data.vue
docker-compose.yml

- Add a memcached wrapper to significantly increase response time
- Add ListCollections and ListData with no query arguments to cache
- Update UI list data call to omit query params for default values in order to hit cache
- Add Map Tile to cache
Closes: https://github.com/openaddresses/batch/issues/137

Coverage Map Updates

---

task/lib/job.js

Ensure http urls aren't treated as buckets

http bug fix

---

api/lib/batch.js
cloudformation/cluster.template.js

Modify Scale DOwn

---

api/lib/upload.js

Somehow the StackName was not capitalized.

Fix Upload

---

api/lib/user.js

We're still getting hit. Adding support for account disabling to give us some breathing room
Ref: https://github.com/openaddresses/batch/pull/162

Account Disable

---

api/doc/api_data.js
api/doc/api_data.json
api/doc/api_project.js
api/doc/api_project.json
api/index.js
api/lib/cacher.js
api/lib/data.js
api/schema/req.body.CreateCollection.json
api/schema/req.body.PatchData.json
api/test/fixtures/get_schema.json
api/web/src/components/Data.vue

Add the ability to manage if sources are to be included in the fabric

Fabric Management

---

api/index.js
api/schema/req.query.SingleUser.json
api/test/fixtures/get_schema.json
api/web/src/components/profile/AdminUser.vue

Add support for manually refreshing the user's level via the Admin UI

Override UI

---

task/Dockerfile

Ref: https://github.com/openaddresses/batch-machine/pull/15

machine 7.9

---

api/index.js
api/lib/schema.js
api/package.json
api/routes/cache.js
api/routes/schema.js

Make using schemas a little less cumbersome by mirroring the router API and letting the Schema class automatically populate the route.

Better Schema

---

api/index.js

Heya, I actually RTFM today for a change 😆 and caught some minor spelling mistakes.

Fix minor spelling/punctuation issues in docs

---

task/lib/validator.js
task/test/validator.test.js

Adds more checks for geometry validity to prevent error encountered in processing CH-Countrywide
Ref: https://github.com/openaddresses/openaddresses/pull/5813

Feature Geometry Check

---

api/lib/schema.js

Added stronger schema input validation for a work project - figured it could help potentially catch some bugs here in the future.

Stronger Route Validation

---

api/index.js

There has been an uptick in 5xx errors. I'm going through the process of diving into the logs and investigating each one.
- Fix edge case where user attempted to reset password of an account that doesn't exist which resulting in `null` being treated as a user object

500 Reduction

---

cloudformation/api.js
cloudformation/batch.template.js
package-lock.json
package.json

Batch-Alarms@2

---

api/lib/job.js
api/package-lock.json
api/package.json
api/routes/job.js
api/test/fixtures/get_schema.json
api/web/src/components/Log.vue

Logs expire via AWS Cloudwatch rules, this adds the ability to download them as a CSV/JSON in order to attach them to a bug report or for personal records

Log Downloading

---

api/doc/api_data.js
api/doc/api_data.json
api/doc/api_project.js
api/doc/api_project.json
api/index.js
api/lib/batch.js
api/lib/schedule.js
api/lib/user.js
api/schema/req.body.CreateUser.json
api/schema/req.body.Schedule.json
api/web/src/components/Register.vue
api/web/src/components/profile/ProfileAdmin.vue
api/web/src/components/profile/admin/AdminActions.vue
task/package-lock.json
task/package.json

- Update TileBase dep in task for fixes in tilebase format
- Add ability to request new email verification from Registration Confirmation page
- Add `fabric` event to MegaQueue
- Add ability to trigger the following from the Admin UI
- Clear the entire MemCached
- Trigger a Fabric Rebuild
- Trigger a Collection Rebuild

Tilebase & Resend Email

---

api/lib/ci.js
task/Dockerfile
task/package-lock.json

Includes: https://github.com/openaddresses/batch-machine/pull/23
Includes: https://github.com/openaddresses/batch-machine/pull/22

batch-machine@7.11.1

---

api/lib/ci.js
api/lib/gh.js
api/lib/schedule.js
api/package-lock.json

More Debug

---

api/lib/run.js
api/package-lock.json
api/routes/run.js
api/test/run.unit.test.js
package-lock.json

Closes: https://github.com/openaddresses/batch/issues/232

Refactor Run

---

api/lib/generic.js
api/lib/level-override.js

Update Generic to latest version

Updated Generic

---

api/web/src/components/Job.vue
api/web/src/components/job/JobSample.vue

Closes: https://github.com/openaddresses/batch/issues/209

Raw Sample

---

api/index.js
api/package-lock.json
api/package.json

Closes: https://github.com/openaddresses/batch/issues/241

Enable CORS

---

api/package-lock.json
api/package.json

General Dep Update that includes better slonik retry query

Slonik Retry

---

api/lib/exporter.js
api/routes/export.js
api/test/exporter.srv.test.js

Generic Exports

---

api/package-lock.json
api/package.json
package-lock.json
task/Dockerfile

:crossed_fingers: Significantly improve the reliability of proper coordinate order in CSV sources. CSV sources that specify an `srs` should now be output as expected.
Ref: https://github.com/openaddresses/batch-machine/releases/tag/7.12.0

Batch-Machine@12

---

api/lib/map.js
api/package-lock.json
api/web/package-lock.json
api/web/package.json
api/web/src/components/Coverage.vue
cloudformation/lib/db.js
package-lock.json

Closes: https://github.com/openaddresses/batch/issues/192

Map Geom Clipping

---

task/lib/job.js

Class is not properly being imported

Fix Failing Job Run

---

api/lib/auth.js
api/lib/user.js
api/package-lock.json
api/routes/collection.js
api/routes/data.js
api/routes/error_job.js
api/routes/export.js
api/routes/job.js
api/routes/level-override.js
api/routes/run.js
api/routes/schedule.js
api/routes/token.js
api/routes/upload.js
api/routes/user.js
api/schema/req.body.PatchUser.json
api/schema/res.ListUsers.json
api/web/src/components/profile/admin/AdminUser.vue
cloudformation/lib/api.js

Add API endpoints/UI necessary to allow an admin to manually mark a user account as verified.
cc/ @iandees

Validate User

---

api/lib/user.js
api/schema/req.query.ListUsers.json
api/web/src/components/profile/admin/AdminUser.vue

More flexible user filtering

---

api/lib/ci.js

Ref: https://github.com/openaddresses/openaddresses/issues/6000

Fix URL Decoding

---

api/Dockerfile
api/package-lock.json
api/package.json
package-lock.json

Ubuntu 22.04

---

.eslintrc.json
cloudformation/batch.template.js
cloudformation/cluster.template.js
cloudformation/lib/api.js
cloudformation/lib/batch.js
cloudformation/lib/db.js
cloudformation/lib/kms.js
cloudformation/lib/schedule.js
cloudformation/lib/secret.js
cloudformation/task.template.js
package-lock.json
package.json
task/collect.js
task/package-lock.json

Update CF Templates to ES6 Modules

Update CF Templates

---

api/lib/ci.js
api/package-lock.json
api/package.json
api/test/ci.unit.test.js

Uncidi has release guidance on mocking fetch now that we can't use nock

Fix Fetch Mocks

---

api/doc/api.js
api/package-lock.json
api/package.json
api/web/package-lock.json
package-lock.json
task/Dockerfile
task/package-lock.json

Update Batch Machine to v8 - settings the required python version to 3.10

Batch Machine @ 8

---

api/web/src/components/MustLogin.vue

typo: authenticatd --> authenticated

---

api/lib/config.js
api/package-lock.json
api/package.json
api/web/package-lock.json
api/web/package.json
cloudformation/batch.template.js
cloudformation/cluster.template.js
cloudformation/lib/api.js
cloudformation/lib/batch.js
cloudformation/lib/db.js
cloudformation/lib/kms.js
cloudformation/lib/schedule.js
cloudformation/lib/secret.js
cloudformation/task.template.js
package-lock.json
package.json
task/collect.js
task/export.js
task/lib/job.js

In an effort to save money, this uploads the content we put on S3 to R2 as well. Once on R2, links to `v2.openaddresses.io` already check R2 before making a request to S3, so this should reduce calls to S3 over time.
@ingalls: I could use some guidance on how to make sure the Cloudflare/R2 credentials flow to the right spots. It looks like I need to add something to the CloudFormation files, but I'm not sure where.

Use S3 API to upload to R2 when we upload to S3

---

README.md
cloudformation/batch.template.js
cloudformation/lib/api.js
cloudformation/lib/batch.js
task/collect.js
task/export.js
task/lib/job.js
task/task.js

Push the R2 bucket env in more places

---

package-lock.json
task/Dockerfile
task/lib/job.js
task/package-lock.json
task/task.js

v9.0.0 removes CSV output and instead natively outputs line delimited GeoJSON.
This PR migrated to use the new output

Native GeoJSON

---

task/Dockerfile
task/package-lock.json

The Preview Module will now render Polygons/Lines in addition to the current points. Previously all geoms were rendered as points

Preview Geoms

---

api/web/src/components/Run.vue
api/web/src/components/Runs.vue

(This is me trying to figure out how to make changes to the Batch website)
There is a "github" pill/label on some of the run pages that seems to link out to Github. It's not clear that this is a link, though, so I'm adding a CSS class to make the browser show a pointer.

Show pointer cursor to indicate you can click on this span

---

api/web/src/components/job/JobMap.vue
api/web/src/components/util/Coverage.vue

Add Mapbox and OSM attribution

---

api/web/src/components/job/JobMap.vue
api/web/src/components/util/Coverage.vue

For https://github.com/openaddresses/batch/pull/392#issuecomment-2181831358

Put attribution control at the bottom of the lower-right control stack

---

api/web/src/components/Data.vue
api/web/src/components/util/Download.vue

- **Update Batch**
- **Less Aggressive Icons**

Less Aggressive Icons

---

README.md
api/lib/config.js
api/lib/types/map.js
api/web/src/components/Fabric.vue
cloudformation/batch.template.js
cloudformation/lib/api.js
cloudformation/lib/batch.js
docker-compose.yml
task/Dockerfile
task/task.js

This switches to use Protomaps for the map in batch. It also pulls in the updated batch-machine image that uses Protomaps to generate preview images.

Use Protomaps for fabric map

---

api/web/src/components/Fabric.vue

The style I used in #410 was old, so switch to a newer one.

Use a newer protomaps style

---

api/web/src/components/job/JobMap.vue
api/web/src/components/util/Coverage.vue

Missed a couple spots that need the new map style

---

api/web/src/components/util/Coverage.vue

Add back the coverage layer that I accidentally deleted

---

task/collect.js

Continues #425 #394 
Fixes problems from incorrect assumptions about the parquet API.

Fix the Parquet schema object

---

task/collect.js

Make most fields of parquet optional

---

task/collect.js

Set row group size so that the buffer doesn't grow indefinitely

---

task/collect.js

Smaller than in #431
Continues #394

Even smaller row group size

---

task/collect.js

Follows #394 
I haven't been able to figure out the memory issues, so this is an attempt to remove some complexity and make it easier to diagnose.

Try skipping the WKB conversion to see if that's causing memory problems

---

task/Dockerfile
task/collect.js
task/package-lock.json
task/package.json

Follows #394 
None of my attempts to generate a Parquet file with Node are working, so giving up and reverting my changes.

Remove DuckDB and attempts to write out Parquet

---

api/lib/types/data.js
api/lib/types/job.js
api/lib/types/joberror.js
api/lib/types/token.js

Remove wildcards to source, layer, and name params

---

api/routes/github.js

Remove the await but keep the tostring
